### ISSUE TITLE
Mod confliction: Pocohud causing studder

### ISSUE THREAD

**Issue by TheHellmare** [segabl/pd2-third-person#12]
Not sure if it's worth it for the creator to look into, but when using pocohud (updated Oct 29th) the third person player animations will studder and glitch 24/7

**Comment by segabl** [comment]
I can have a look at it when I get a chance. Chances are some of pocos network code is still outdated.

**Comment by Sydch** [comment]
Using andole's latest pocohud variation, no problems i've got in to "glitched" so far. (Only have a problem about getting down makes animation gone, which is already reported and doesn't related with pocohud)

**Comment by TheHellmare** [comment]
I can certainly try messing around with the two some more to see if I can find something. I was using a community update addon to the mod which allowed it to work with BLT2.0 (after taking ages for the mod to update officially) because it added additional poco-rose functions. I can see if that was the problem. Because with an outdated pocohud with addon the mod and game worked fine albeit more crashes. Latest version just stutters everything

**Comment by TheHellmare** [comment]
Just tried vanilla poco once more on the most recent of it's updates and yeah, that seems to be the culprit. Removing the folder fixed stuttering. Something with Pocohud is causing a confliction which causes the character to glitch similar to when driving with the mod.

**Comment by segabl** [comment]
I haven't used Poco in a while given how unstable it was after all the updates, with only some fixes so I'm not sure if it's worth looking into it given that it seems to work for some and for others it doesn't.

**Comment by TheHellmare** [comment]
Found the issue! When using Pocohud's desync feature found in the mod's settings it causes stuttering to the player. Turning this off fixes this. Not sure if you want to add it to the mod page or not, but that's the fix. Feel free to clear this from the issues list.

**Comment by segabl** [comment]
Yeah you shouldn't be using that feature anymore anyways. Good to see you've found the issue though.

**Comment by TheHellmare** [comment]
It was on likely because you never have to replace the save file which keeps the settings as you configure them to be.
