### ISSUE TITLE
Problem when hosting pubs

### ISSUE THREAD

**Issue by Men10doh2** [segabl/pd2-third-person#14]
I have just been accused of hacking due to a bug in the mod or game.
Some random guy with a mic joined (i wont give his name) mid game on a First world bank heist.
He first noted that the cops were "Slow" and didn't shoot him. then he noted that there was a second me in the game a few feet from me standing staring at a wall. and then he got very rude and started calling me a hacker and insisted that I was using Pirate perfection. it was a very sad and anger enducing moment for me. But i want this to stop. I searched on the steam forums for any cloning bug in the game and came up empty. What can I do to help you understand my perdicament.
BTW this only happens when Third Person is active.
And I'm sorry if I sound rude, I'm still cooling off from the Hacusation.

**Comment by Men10doh2** [comment]
My heart's racing and my hands are shaking (from anger) it's a bit hard to type sorry if there's any spelling errors or anything

**Comment by Men10doh2** [comment]
i still love the mod though

**Comment by segabl** [comment]
Yes I've had another report from someone with a similar issue. I think it only happens when people join mid-game, so if you're easily angered by other people saying you're a hacker I would disable ingame joining until I figure out how and if this is avoidable.

**Comment by Men10doh2** [comment]
Take your time buddy it's not really REALLY important to fix, just a minor bug.

**Comment by segabl** [comment]
After having a quick look at it today it doesn't appear as if it's possible to fix this issue. I will however keep this issue open and see what I can find.

**Comment by Men10doh2** [comment]
ok

**Comment by segabl** [comment]
has been fixed a while ago
