### ISSUE TITLE
Animation bug when getting cuffed

### ISSUE THREAD

**Issue by TheHellmare** [segabl/pd2-third-person#16]
When getting cuffed the player will just stand still until they are rescued or break free in which they will then be stuck in a cuffed state visually. They can move, and this eventually will change to a jumping stance, but from there forward the player movement animations are frozen.

**Comment by segabl** [comment]
Yeah there are some animation problems with different states, I'm aware of that. Still trying to find out why it happens and how to avoid it, but I don't have a lot of time atm.

**Comment by segabl** [comment]
Partly fixed by https://github.com/segabl/pd2-third-person/commit/76281c6a83017978165d026135b7cb868f949776, animation for being cuffed is still incorrect but animations return when being freed.
