### ISSUE TITLE
The mod is not compatible with NBGTO mod's kicking feature

### ISSUE THREAD

**Issue by PJzuza** [segabl/pd2-third-person#18]
Crash.txt
-------------------------------

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                 set_running()  lib/units/beings/player/states/playerstandard.lua:4482  
       _start_action_running()  lib/units/beings/player/states/playerstandard.lua:1541  
           _check_action_run()  lib/units/beings/player/states/playerstandard.lua:4454  
       _update_check_actions()  lib/units/beings/player/states/playerstandard.lua:930  
                      update()  lib/units/beings/player/states/playerstandard.lua:424  
                                lib/units/beings/player/playermovement.lua:318      

-------------------------------

System information:
	Application version : 1.85.486.
	CPU : Intel(R) Core(TM) i5 CPU 750 @ 2.67GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 750 Ti / nvd3dum.dll[22.21.13.8569]
	Language : english
	Memory :     8155MB 504KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (JBL Pebbles))

-------------------------------
I have the hour filter feature on NBGTO and it will kick a player who has lower gameplay hours than in the hour filter. NBGTO mod works as it should be but if I have used this mod too. After the player get kicked. The game will be crashed and there will be a crash log like above. It happens in every heists as far as I have tested. 

And I am sure it is this mod because I've taken off Third Person mod and I have kept other mods (Including Full speed swarm mods, WolfHud, NBGTO and Cheater Kicker ) no crash.

**Comment by segabl** [comment]
Not sure why it happens, I wmight have a fix though

**Comment by segabl** [comment]
Not sure how this would effect the mod. Can't guarantee anything about this issue

**Comment by PJzuza** [comment]
@segabl I understand. Although this can be reproducible and it is pretty annoyed that I have to manually kick peopel instead of auto kick from using NBGTO mod. Video will be added soon.

**Comment by DeadneM** [comment]
does it happen when you are in fps ? tps ? or both ?
also it happens also in lobby ?

**Comment by PJzuza** [comment]
@DeadneM Do you mean in 1st person or 3rd person? Both. the mode is not a problem. It's something else

For the second question. No. No crash there but there is something more weird happened... 
[Youtube's link](https://youtu.be/ohtpYT8Wb6s)
A video can explain better than I said it myself I think... 

Short version: In a lobby my character sometimes got swapped with the one who joined me and I could even see when they sent me a chat box message. It happened only when I have NBGTO auto kicked feature + Third Person mods ON. If only NBGTO mods then everything is fine.

**Comment by segabl** [comment]
Not sure how this happens. I'll check this.

**Comment by PJzuza** [comment]
@segabl I'm still trying to figure out this issue. I've lowered the MenuManager.lua in NBGTO mod at line 
`--DelayedCalls:Add("NoobJoin:Delayed_Kick_" .. id .. "_2", 10, function()  Into
DelayedCalls:Add("NoobJoin:Delayed_Kick_" .. id .. "_2", 2, function() --lower the time to kick him out of the lobby in case it may help but no luck...`  
Now I got like 2 different crashes... probably more in the future  
[My new crash#1](https://pastebin.com/paaH23g1)  
The first one poped up while I was trying to kick a hidden profile player.  
[My new crash#2](https://pastebin.com/CLtcBfi2)  
The second one came from the time where someone tried to join my lobby and got kicked by NBGTO but I still see his equipment and weapons on my loadout screen...  

Any idea what maybe the cause?

**Comment by segabl** [comment]
Not really. I still can't think of a reason why those two mods would clash. At that point in time third person isn't even used yet so idk.

**Comment by PJzuza** [comment]
@segabl Yeah that's pretty weird... But I feel that Third Person is related on the in-game aka while playing in a heist. Like people who got kicked still see a lobby as normal instead of being kicked out. tbh I've no idea where I should try or test it...

**Comment by segabl** [comment]
It might be that NGBTO is hooking some functions this mod also hooks and does so improperly? I don't have time to look at NGBTOs code atm but that's the only thing I can think of

**Comment by PJzuza** [comment]
@segabl You are right. I mean it could be both and NBGTO mod is very outdated and Fishtaco won't update his mods anymore sadly. I guess it may have to rewritten the whole codes again sooner or later. Though I don't get the different crashlogs I got... Ik how to reproduce it but I don't get how both mods will have a conflict to cause this annoying crash issue.
