### ISSUE TITLE
3rd person view and 1st person view aiming is not the same position

### ISSUE THREAD

**Issue by PJzuza** [segabl/pd2-third-person#19]
[Video](https://youtu.be/LnoPLMLf7Dw)  

Sorry if this is in the known issue about "Aiming in third person is difficult since the aim point is not the screen center"

**Comment by segabl** [comment]
Well this is a side effect, the closer you are to the position you shoot at, the more misleading it looks. Not really a way to fix it, but enabling the crosshair option will show you that the actual aiming position is correct.
