### ISSUE TITLE
Need new hitmaker

### ISSUE THREAD

**Issue by chromKa** [segabl/pd2-third-person#20]
Subject. Aim from 3rd person no good.

**Comment by segabl** [comment]
What do you mean exactly? There's not really a way to change aiming for 3rd person, all I can do is add a 3rd person crosshair (which I have done).

**Comment by chromKa** [comment]
I mean that shooting at the enemy has problems, because the aiming is not accurate

**Comment by segabl** [comment]
The current solution is the best I can do without making shots come from an incorrect position. This is something that naturally happens when you do third person on a game that's not intended to be played that way.
