### ISSUE TITLE
Crash after connect to server

### ISSUE THREAD

**Issue by chromKa** [segabl/pd2-third-person#25]
`Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                                lib/units/cameras/fpcameraplayerbase.lua:1827       
               play_redirect()                                                      
                          =[C]  play_redirect()                                     
                                lib/units/cameras/fpcameraplayerbase.lua:1228       
               play_redirect()                                                      
lib/units/beings/player/playercamera.lua:129  _start_action_equip()                               
                                lib/units/beings/player/states/playerstandard.lua:1712  
                      _enter()                                                      
lib/units/beings/player/states/playerstandard.lua:286  enter_original()                                    
                                lib/units/beings/player/states/playerstandard.lua:205  
                       enter()                                                      
@mods/WolfHud/lua/Interaction.lua:75  change_state()                                      
                                lib/units/beings/player/playermovement.lua:302      
        _change_player_state()                                                      
lib/managers/playermanager.lua:952  spawned_player_original()                           
                                lib/managers/playermanager.lua:928                  
              spawned_player()                                                      
@mods/WolfHud/lua/GameInfoManager.lua:2734  set_unit_original()                                 
                                lib/network/base/networkpeer.lua:2285               
                    set_unit()                                                      
                   @mods/Third  Person/lua/networkpeer.lua:11                       
                                lib/network/handlers/unitnetworkhandler.lua:48      `

**Comment by segabl** [comment]
Does it happen always?

**Comment by chromKa** [comment]
no

**Comment by segabl** [comment]
Then I'll need a bit more information about what game you joined, weapons, etc
