### ISSUE TITLE
[Possible bug] Disbled Starts in third person option but a player still turned back into the third person mode.

### ISSUE THREAD

**Issue by PJzuza** [segabl/pd2-third-person#29]
I think this is a bug. Here is how to reproduce it.  
- If "Starts in third person" hasn't been checked but "Aiming down sights activates first person" has been checked.  
- When starting a heist in the first person mode(while this mod is still enabled of course) If the player use a weapon. Any weapons I think. Then hold right mouse button to aim then release it. The view will become the third person mode again.  

Note that I'm not sure much though cause I've other mods as well.

**Comment by Sydch** [comment]
I can confirm this, because I've exact same issue.

**Comment by PJzuza** [comment]
@segabl Thanks and no more issue :D so let me close this Issue thread.
From the [71st commit](https://github.com/segabl/pd2-third-person/commit/9eb7a8ab5ae62810d6c95b3eb3bfba5e4342cb38)
