### ISSUE TITLE
Switching To Angled Sight Makes Running With Gun Animation Gone

### ISSUE THREAD

**Issue by Sydch** [segabl/pd2-third-person#3]
it looks like i've own lock'n load skill. switching back to normal sight fixes the issue til switching back in to angled sight again.

**Comment by segabl** [comment]
Not sure if this is a bug with the mod or just how the animations for the angled sight work. I will check this.

**Comment by DeadneM** [comment]
It does that. As soon as you have a gadget enabled. Laser light or angled sight. I think it's how the game work. And fix it would means useless torchlight as it will move around

**Comment by segabl** [comment]
Thanks for the confirmation. Seeing as it is just how it works in the base game, I will close this.
