### ISSUE TITLE
Multijump issue

### ISSUE THREAD

**Issue by chromKa** [segabl/pd2-third-person#4]
Application has crashed: C++ exception
[string "lib/network/base/handlers/basenetworkhandler.lua"]:46: attempt to index local 'rpc' (a nil value)

SCRIPT STACK

_verify_character_and_sender() lib/network/base/handlers/basenetworkhandler.lua:63
lib/network/handlers/unitnetworkhandler.lua:176
send_to_peers_synched() @mods/Third Person/lua/basenetworksession.lua:52
send() lib/network/base/extensions/networkbaseextension.lua:11
_update_network_jump() lib/units/beings/player/states/playerstandard.lua:4002
_update_movement() lib/units/beings/player/states/playerstandard.lua:1087
original() lib/units/beings/player/states/playerstandard.lua:422
update_original() @mods/base/req/core/Hooks.lua:260
update_original() @mods/Seamlink Gameplay Overhaul/lua/sliding.lua:51
update() @mods/WolfHud/lua/BurstFire.lua:212
lib/units/beings/player/playermovement.lua:275

**Comment by segabl** [comment]
I would appreciate a meaningful title and a bit of information about what you were doing when this happened. As in, what weapons you used, what character, when did it occur, etc. I can't really make anything out of this plain crashlog.

**Comment by NANI-SORE** [comment]
I have the same crash when using [Multijump](https://github.com/DrNewbie/Mess/tree/master/mods/MultiJump) mod

**Comment by segabl** [comment]
I think I see why it happens but it seems to be a problem with Multijump. If I'm correct clients would also crash when you use it.

**Comment by chromKa** [comment]
yes, Multijump by Seamlink Gameplay Overhaul mod.
Plz fix soon :)

**Comment by segabl** [comment]
Probably fixed by https://github.com/segabl/pd2-third-person/commit/31a435f57e1c767bdf01996401d283363cf51da2?

**Comment by NANI-SORE** [comment]
Can confirm, doesn't crash after the fix
