### ISSUE TITLE
Keybindings Doesn't Work In My End

### ISSUE THREAD

**Issue by Sydch** [segabl/pd2-third-person#6]
I don't know why it happens, but i'll try to help. I suppose it's a mod conflict issue, because no one mentions this issue before.

**Comment by segabl** [comment]
No, other people have had the issue I guess. Do the keybinds just not work or do they not even show up in the menu?

**Comment by Sydch** [comment]
They show up and set-able in menu, it doesn't work out in game. Pressing setted keys are doing nothing.

**Comment by segabl** [comment]
Hm, that is weird, you might want to check the BLT log for anything suspicious.

**Comment by Sydch** [comment]
Checked it out after you mentioned it, nothing suspicious happened. `11:15:04 PM Lua: Found a json error, attempting to use old json loader!
11:15:05 PM Lua: [Keybind] Registered keybind [BLTKeybind mui_voice_keybind]
11:15:05 PM Lua: [Keybind] Registered keybind [BLTKeybind mui_hud_keybind]
11:15:05 PM Lua: [Keybind] Registered keybind [BLTKeybind mui_info_keybind]
11:15:05 PM Lua: [Keybind] Registered keybind [BLTKeybind toggle_cam_mode]
11:15:05 PM Lua: [Keybind] Bound toggle_cam_mode to `
11:15:05 PM Lua: [Keybind] Registered keybind [BLTKeybind flip_camera_side]
11:15:05 PM Lua: [Keybind] Bound flip_camera_side to left alt
11:15:05 PM Lua: [Keybind] Registered keybind [BLTKeybind NewbieDW_keybind_id]
11:15:05 PM Lua: [Keybind] Registered keybind [BLTKeybind Newbie_Skill_Info_id]
11:15:05 PM Lua: [Keybind] Registered keybind [BLTKeybind NGBTO_manual_ban]
11:15:05 PM Lua: [Keybind] Registered keybind [BLTKeybind NGBTO_inspect]
11:15:06 PM Lua: [Menus][Warning] Parent menu for child 'bagcontour_customize' is null, ignoring...    1
11:15:06 PM Lua: 27
11:15:06 PM Lua: Poco:Init
11:15:06 PM Lua: Locale EN loaded
11:15:06 PM Lua: 27
11:15:06 PM Lua: [BeardLib] Could not find any source for track nil and event pb_still_breathing current custom track is nil
11:15:06 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request`
Only this part mentions the mod, you can check it out.

**Comment by segabl** [comment]
Weird, it seems to bind the keys correctly. And I don't assume any errors show up in the BLT log after pressing one of the binds?

**Comment by Sydch** [comment]
Yeah, no errors. I spam those keys like hell, still no errors shows up.

**Comment by segabl** [comment]
Not really sure what could be causing it then, sorry. I assume you have the latest version of BLT.

**Comment by Sydch** [comment]
Yup latest version of BLT. Is it got some kind of improved one in GitHub or anywhere else?
Also I don't know the mod requires BeardLib but I don't have probably latest one of it.

**Comment by segabl** [comment]
If you got the latest one from [here](https://github.com/JamesWilko/Payday-2-BLT/releases) you should be good. The mod doesn't require BeardLib. Maybe you can try disabling all mods but this one for testing if the keybinds not working is a mod conflict.

**Comment by Sydch** [comment]
Issue has been fixed with one of the latest installments after 4.12.17. Don't know why it happened, but it's done.
