### ISSUE TITLE
Contourtext.lua

### ISSUE THREAD

**Issue by DeadneM** [segabl/pd2-third-person#7]
V0.5
Using "Remove Teammates Outline" from dr_newbie "http://modwork.shop/21420" make the game crash
the mod just remove the outlines on team mate. here's the crashlog

`
Mon Dec 04 23:06:42 2017

Application has crashed: C++ exception
[string "lib/units/contourext.lua"]:412: bad argument #1 to 'ipairs' (table expected, got nil)

SCRIPT STACK

_remove() lib/units/contourext.lua:412
remove() lib/units/contourext.lua:341
setup_unit() @mods/Third Person/thirdperson.lua:205
set_unit() @mods/Third Person/lua/networkpeer.lua:9
spawn_unit_original() lib/network/base/networkpeer.lua:2132
spawn_unit() @mods/Bot Weapons/lua/networkpeer.lua:5
spawn_players() lib/network/base/basenetworksession.lua:1498
update_original() lib/states/ingamewaitingforplayers.lua:262
update_actual() @mods/WolfHUD/lua/MenuTweaks.lua:592
Run() @mods/TranslucentMissionBriefingGUI/ingamewaitingforplayers.lua:145
update() @mods/PocoHud3/poco/../poco/Hud3.lua:2953
update() core/lib/utils/game_state_machine/coregamestatemachine.lua:92
update() lib/setups/setup.lua:784
update() lib/setups/gamesetup.lua:654
_update() lib/setups/networkgamesetup.lua:21
update() @mods\PocoHud3\poco\common.lua:310
core/lib/setups/coresetup.lua:537

-------------------------------`

**Comment by segabl** [comment]
I can see why it happens, will push a fix for this.

**Comment by DeadneM** [comment]
The line 205 of thirdperson.lua is to remove outlines? 
It's not working for me. 

I have fixed it by adding the dr_newbie code instead of this line. And adding the contour hooks in mod txt

If the goal of the line 205 was to remove the outline on ia i can do a push request with my change. It's working great.

**Comment by segabl** [comment]
I don't want to change this code as it should work in normal conditions. Dr Newbie's code on the other hand could be easily fixed by hooking to the ContourExt:add function. I might create a PR on his repo.

**Comment by DeadneM** [comment]
Thanks I'll look on my side too

**Comment by segabl** [comment]
You could try these changes from my pull request to Dr Newbies code: https://github.com/DrNewbie/Mess/pull/1 and see if that works

**Comment by DeadneM** [comment]
It works perfectly thanks. I'll try to remove some more outlines too ^^ looks easy
