### ISSUE TITLE
No weapon crash the game

### ISSUE THREAD

**Issue by DeadneM** [segabl/pd2-third-person#8]
v0.5
using the no weapon mod https://modworkshop.net/mydownloads.php?action=view_down&did=18961
its a custom weapon addon that just create an empty weapon. switching to this weapon crash the game.
the vulcan minigun is displayed when on tps when playing with others

heres the crashlog

Mon Dec 04 23:12:17 2017

Application has crashed: C++ exception
[string "core/lib/utils/corestring.lua"]:63: bad argument #1 to 'gmatch' (string expected, got nil)

SCRIPT STACK

split() core/lib/utils/corestring.lua:63
add_unit_by_factory_name() lib/units/beings/player/huskplayerinventory.lua:98
_perform_switch_equipped_weapon() @mods/Third Person/thirdperson.lua:183
synch_equipped_weapon() lib/units/beings/player/huskplayerinventory.lua:20
lib/network/handlers/unitnetworkhandler.lua:74
send_to_peers_synched() @mods/Third Person/lua/basenetworksession.lua:52
send() lib/network/base/extensions/networkbaseextension.lua:11
_send_equipped_weapon() lib/units/beings/player/playerinventory.lua:374
equip_next() lib/units/beings/player/playerinventory.lua:330
_start_action_equip_weapon() lib/units/beings/player/states/playerstandard.lua:5045
_start_action_equip_weapon() @mods/GoonMod Weapon Customizer Standalone/lua/PlayerStandard.lua:12
_update_equip_weapon_timers_original() lib/units/beings/player/states/playerstandard.lua:3201
_update_equip_weapon_timers() @mods/WolfHUD/lua/GameInfoManager.lua:3461
_update_check_actions() lib/units/beings/player/states/playerstandard.lua:821
update_original() lib/units/beings/player/states/playerstandard.lua:414
master_PlayerStandard_update() @mods/WolfHUD/lua/BurstFire.lua:212
update() @mods/Carry-Stacker-Reloaded/lua/playerstandard.lua:7
lib/units/beings/player/playermovement.lua:275

-------------------------------

**Comment by segabl** [comment]
I'll see what I can do

**Comment by segabl** [comment]
Could you also check your BLT log for any messages by ThirdPerson please?

**Comment by segabl** [comment]
Fixed with https://github.com/segabl/pd2-third-person/commit/6c629ec71e98aeefe6d2f493829b1c56efdc18e7
