### ISSUE TITLE
basenetworkhandler.lua

### ISSUE THREAD

**Issue by chromKa** [segabl/pd2-third-person#9]
Application has crashed: C++ exception
[string "lib/network/base/handlers/basenetworkhandler.lua"]:46: attempt to index local 'rpc' (a nil value)

SCRIPT STACK

lib/network/base/handlers/connectionnetworkhandler.lua:598

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

**Comment by segabl** [comment]
Trying to fix this atm

**Comment by segabl** [comment]
Fixed with https://github.com/segabl/pd2-third-person/commit/dfc10ce4dc4a60e5177aac81640055236c795152
